### ISSUE TITLE
EGKB-Biggin Hill Airport-ENGLAND-UNITED KINGDOM

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Airports#968] opened 2016-07-27 21:03 UTC
Will redo this one

**Comment by PaulNielsen** [comment] 2016-07-27 21:08
Sorry, when I searched for it. Nothing showed up, but I noticed 5 seconds after my internet went out, so that's probably why. Sorry.

**Comment by kilt46** [comment] 2016-07-29 14:38
![image](https://cloud.githubusercontent.com/assets/14023167/17251917/2e2f309c-5570-11e6-85a2-e7fa51189d04.png)

**Comment by kilt46** [comment] 2016-08-05 02:46
![image](https://cloud.githubusercontent.com/assets/14023167/17424759/b23171fe-5a8c-11e6-8b9a-971d9c3787a5.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17424781/d72849c4-5a8c-11e6-863b-b4e194e245ee.png)
![image](https://cloud.githubusercontent.com/assets/14023167/17424792/e551bbd4-5a8c-11e6-8292-e34bb94ddde7.png)

**Comment by ItsW1ll** [comment] 2017-07-17 21:04
Runway 11/19 has been permanently withdrawn from use see http://www.nats-uk.ead-it.com/aip/current/amend28/EG_Amdt_A_2017_08_en.pdf page 287

**Comment by ItsW1ll** [comment] 2017-10-10 21:20
File has bee committed, can we close this?

**Comment by moritzbabl** [comment] 2017-10-10 21:23
Well, the issue is already closed

**Comment by kilt46** [comment] 2017-11-13 23:37
![image](https://user-images.githubusercontent.com/14023167/32755111-5e88ed3a-c899-11e7-92e3-72cbbbe48573.png)

**Comment by ItsW1ll** [comment] 2019-01-23 10:12
Google earth released new imagery, so will be adding necessary changes to the airport layout

**Comment by ItsW1ll** [comment] 2019-01-25 11:39
Removed in a9782f5

**Closed** 2019-01-27 10:03 UTC
Labels: Design Issue

**Comment by kilt46** [comment] 2019-01-27 13:02
![image](https://user-images.githubusercontent.com/14023167/51801298-78e38880-2201-11e9-928b-c19437b93a01.png)
