### ISSUE TITLE
CGCS - Union Glacier - Antarctica

### ISSUE THREAD

**Issue by RobertineIFC** [InfiniteFlightAirportEditing/Airports#6659] opened 2021-02-18 05:31 UTC
# Airport Name
Union Glacier Blue Ice
# Country?
Antarctica 
# Improvements that need to be made?
It doesn't exist yet, make from scratch
# Are you working on this airport?
YES
# Airport Priority? (10000ft+ Runway, Low)
Low

**Comment by ECoops-123** [comment] 2021-02-18 05:39
Seems to be a duplicate of what you're already assigned to.

#5272 

I didn't see this myself. If you're willing to do a nearby Chilean airport, SCPZ that can also be changed, or this will be recycled to the next airport.

**Comment by MajorTomMueller** [comment] 2021-02-18 05:55
ICAO code not found anywhere  else in the World Wide Web. 
Union Galcier is already covered in the topic ecoops mentioned. 
in addition you have already three assigned issues.

**Closed by MajorTomMueller** 2021-02-18 05:55 UTC
