### ISSUE TITLE
KSMO-Santa Monica Municipal Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by Misha16** [InfiniteFlightAirportEditing/Airports#250] opened 2015-08-13 10:00 UTC
Several noncurved taxiways. Not enough parking

**Comment by Swang007** [comment] 2015-11-16 00:52
https://community.infinite-flight.com/t/santa-monica-airport-runway-border-line/15124

**Comment by cboisselier** [comment] 2015-12-26 02:03
Could someone check that? I think the problem is that a part of the taxiway is ON the runway...? I can't figure that out #newbie

**Comment by HenrikBerg02** [comment] 2015-12-26 02:11
I'll check it out.

**Comment by kilt46** [comment] 2015-12-26 16:45
Center lines removed next to runway.

**Comment by kilt46** [comment] 2016-12-10 17:52
![image](https://cloud.githubusercontent.com/assets/14023167/21075095/2e4cff5a-becf-11e6-8ccb-ed2bb61d56cd.png)

**Comment by danisrils39** [comment] 2020-06-17 20:55
I see this is open, I guess I can grab and bring it up to standard

**Comment by MajorTomMueller** [comment] 2020-06-18 18:42
@dhamilton30 are you still working on this? 
Respond with in a week, otherwise I will assign @danisrils39.

**Comment by dhamilton30** [comment] 2020-06-19 01:13
I was working on it, but due to a change in my work schedule, my
availability has drastically decreased.  Please feel free to reassign.  My
apologies.

**Closed** 2020-09-20 18:29 UTC

**Comment by kilt46** [comment] 2020-09-21 00:33
![image](https://user-images.githubusercontent.com/14023167/93725872-2c885180-fb78-11ea-80ed-03fd042eeaf8.png)
