### ISSUE TITLE
ZSWX -Sunan Shuofang Airport-JIANGSU-CHINA

### ISSUE THREAD

**Issue by eltonfly** [InfiniteFlightAirportEditing/Airports#3570] opened 2019-01-03 03:04 UTC
# Airport Name

Sunan Shuofang International Airport

# Country?

China

# Improvements that need to be made?

Will be redone from scratch

# Are you working on this airport?

No

# Airport Priority? (A380, 10000ft+ Runway)

The length of runway 03/21 is more than 3200M

**Comment by brunocr98** [comment] 2019-01-03 03:16
So, you literally said in the 2nd question that you’ll do it, but then you contradicted yourself in the 3rd question by saying “no.” Is this a suggestion for us or you’re really going to do it?

**Comment by eltonfly** [comment] 2019-01-03 04:38
the question "Are you working on this airport?" and I say no. I thought this meant asking if I was an airport worker. I am not a worker in this airport but I will edit it.

**Comment by AnthonyCK** [comment] 2020-04-01 15:05
Can anyone assign this issue to me? Working on it.
![image](https://user-images.githubusercontent.com/37546244/78153058-3fde1e00-746d-11ea-83d1-7468749f9b2d.png)

**Comment by bavariaaviation** [comment] 2020-04-01 15:34
@AnthonyCK the issue is already assigned to @eltonfly . Is there an agreement between the two of you who is working on it?

**Comment by AnthonyCK** [comment] 2020-04-01 15:47
Since @eltonfly's last contribution was commenting on this issue a year ago, with no progress at this airport along the year, I started making it, and it was basically completed. @bavariaaviation

**Comment by bavariaaviation** [comment] 2020-04-01 15:48
Fair enough.

**Comment by AnthonyCK** [comment] 2020-04-03 01:57
Sent to OR

**Closed** 2020-04-03 02:23 UTC

**Comment by MBeringuy** [comment] 2020-04-03 20:43
![Untitled-1](https://user-images.githubusercontent.com/32115399/78403376-a29cfa00-75d2-11ea-92de-f7d84c699728.jpg)
