### ISSUE TITLE
KJFK-John F. Kennedy International Airport-NEW YORK-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#26] opened 2015-01-05 10:47 UTC

**Comment by NickArt1342** [comment] 2016-06-01 06:44
As my issue has been closed and refurbished, I'm writting this message here to if you have any issue with this airports or questions, you should contact me.

**Comment by IFAEpat** [comment] 2016-06-24 03:32
White lines around buildings and @NickArt1342 's signature should be removed
![screen shot 2016-06-23 at 11 26 11 pm](https://cloud.githubusercontent.com/assets/18223248/16327125/b31791a6-399a-11e6-8d5c-f4887da8a394.png)

**Comment by NickArt1342** [comment] 2016-06-24 13:25
The stated issues have already been addressed @IFAEpat Please contact me directly regarding my airports next time.

**Comment by dushyants19** [comment] 2016-07-04 13:30
Full of hashed regions, Transparent twys, over lapping twys, too many roads, White lines around buildings.

**Comment by dushyants19** [comment] 2016-07-04 13:32
And a rumored/possible `Nick Art` Signature

**Comment by samuelandersson** [comment] 2016-07-17 20:14
@NickArt1342 How's this going?

**Comment by TristinWoolf** [comment] 2016-08-24 23:18
I can confirm that the hashed regions are still there, as seen on a user screenshot on IFFG. Any word @NickArt1342

**Comment by Hamza1108** [comment] 2016-09-07 00:23
Is this available

**Comment by kilt46** [comment] 2016-09-07 00:26
As you will see it is assigned to Nickart

**Comment by kilt46** [comment] 2016-09-18 14:37
![image](https://cloud.githubusercontent.com/assets/14023167/18616515/e62a319e-7d82-11e6-83d5-f032da28d56e.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18616524/20d38fca-7d83-11e6-8f53-7f8c2670ef3a.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18616533/482162c8-7d83-11e6-9f7b-5b6699a28008.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18616544/6b818c48-7d83-11e6-868c-4cf332d05972.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18616550/776a0f6c-7d83-11e6-83de-f1f771e788f7.png)
![image](https://cloud.githubusercontent.com/assets/14023167/18616555/8181cabc-7d83-11e6-9f81-066a3f836109.png)

**Comment by NickArt1342** [comment] 2016-09-18 22:16
Please let's have a moment of silence for all the hatched line areas that had to be removed to day. We shall never forget them. :(

**Comment by moritzbabl** [comment] 2017-04-21 22:59
The airport needs more love, there are no holes cut for terminals and patches making them invisible in IF, also the size of the file could be reduced by adding a new version using less separate taxiways

**Comment by NickArt1342** [comment] 2017-04-27 10:47
I'm not exactly sure how messed up this file became since I last checked it. Also I still need to know how the new rendering of IF works...

**Comment by dushyants19** [comment] 2017-04-27 12:26
Nothing great Nick. Just don't overlap taxiways and cut holes. That should do just fine. 

Your version of JFK was a mess. It did more bad than good, it lags so much.. Sorry Nick.

**Comment by NickArt1342** [comment] 2017-04-27 19:42
Excuse me?!? Have you even seen the old version of KJFK? Also my version of it is *not* a mess. It looked perfect and was at its time the most detailed airport of IF. This airport even featured perfect hashed line areas, that were perfectly identical with the real airport, every line is as it should be in reality and so is every asphalt and concrete, I don't know where there is an area where I should cut holes, because every concrete taxiway already has a hole cut for the asphalt.

**Comment by carmichaelalonso** [comment] 2017-04-27 19:45
Seeing as I got the notification email, I'll chip in: no hashed lines please. It would be good to simplify this a bit - whilst realism is key, so is performance, and unnecessary features are best left out until a time where airport rendering supports more features. Please keep these issues civil else I'll close and do the airport myself (and I can assure you nobody wants that).

**Comment by NickArt1342** [comment] 2017-04-27 19:48
@cameron The hashed lines as well as the white building outlines got removed long ago (What a waste in my opinion) Also if you (Dush) can't run IF properly that's not my problem. It works perfectly fine for me. That comment really angered me.

**Comment by kilt46** [comment] 2017-06-04 15:04
Needs to be as per chart below
![image](https://cloud.githubusercontent.com/assets/14023167/26762763/360c3616-490d-11e7-88e3-cc08736e5b9a.png)

**Comment by kilt46** [comment] 2017-06-04 15:05
If you cannot get this done please let me know and I will take over! I know you are working many many Swiss airports!

**Comment by kilt46** [comment] 2017-06-04 15:35
This airport has taxiway over taxiway over taxiway. No holes cut. Transparent taxiways for lines! Really needs done from scratch!!

**Comment by NickArt1342** [comment] 2017-06-04 21:10
I dare you, most of it is perfect already. Just look at how beautiful all the side lines are. As for the taxiways I think I now know what you mean but I'm not entirely sure. It would really help if I'd get a more detailed description other than "They need holes cut". Concrete always goes over asphalt so this has never been an issue. Please show me what taxiways need to be corrected. I checked the airport in IF and I just don't see ANY issue with it. Keep in mind that airport was started and done a long time ago.

**Comment by dushyants19** [comment] 2017-06-05 04:06
"Concrete always goes over asphalt so this has never been an issue. " No there's an issue. We started enforcing it in our emails from last June, and almost every editor is following this.. this is why we keep our airports future-proof.

Since global, the way of rendering has changed. Concrete is no longer above asphalt.. this isn't the old days nick.

**Comment by NickArt1342** [comment] 2017-06-05 08:15
well duh, you could have... you know... told me that? How is it rendered newly then?

**Comment by dushyants19** [comment] 2017-06-05 08:29
That's what @moritzbabl said, you just didn't care to listen. It's rendered "As in WED" according to @ValXp but that isn't the case

**Comment by NickArt1342** [comment] 2017-06-05 09:10
... I don't see any comment of his on this issue. Also you still failed to tell me how it's rendered now, which is basically all i'm asking for.

**Comment by moritzbabl** [comment] 2017-06-05 09:45
NOT. CONCRETE. OVER. ASPHALT.

**Comment by NickArt1342** [comment] 2017-06-05 19:27
@moritzbabl Your aggressivity is unnecessary and contraproductive.

**Comment by ewanfleming** [comment] 2017-06-05 19:42
Keep your pants on guys... 🙄
In all seriousness, we need to keep this professional and aviod arguments like this

**Comment by kilt46** [comment] 2017-06-05 22:52
Transparent taxiways SHOULD NOT BE THERE. Use lines!!!!
![image](https://cloud.githubusercontent.com/assets/14023167/26806672/c9a8f41c-4a17-11e7-8a24-28145082b5f7.png)

**Comment by kilt46** [comment] 2017-06-05 22:54
HOLES for Most terminals have not been cut!

**Comment by kilt46** [comment] 2017-06-05 22:55
IF you DARE me I WILL redo from scratch!!!

**Comment by NickArt1342** [comment] 2017-06-09 10:02
@Kilt I have an offer. I could persuade myself to agree to let you play around with my KJFK. But only on certain conditions. Are you interested?

**Comment by kilt46** [comment] 2017-06-09 13:59
Please be aware that KJFK or any airport, once published on this site is the property of Infinite Flight. The intention of the editing community is to continually improve the quality and portfolio of the airports. If you can rectify this airport by reducing the number of layers (fitting taxiways/aprons) so that there is only one layer (hence reducing memory and geometry clashes in a timely manner, everyone would be happy. If you would prefer that someone else takes on this workload due to your overbearing time commitments, we will make it so. The intent here is to leave as much of the live artwork intact as is!

**Comment by NickArt1342** [comment] 2017-06-09 14:44
That's not 100% right what you're saying. Here you have the relevant passage in the license agreement: "You grant to "The Company" (Flying Development Studio LLC) a non-exclusive, irrevocable, worldwide, royalty-free, sublicenseable, relicenseable, transferable license under all of Your relevant intellectual property rights, to use, copy, prepare derivative works of, distribute and publicly perform and display "The Contributions" on any licensing terms, including without limitation: (a) open source licenses like the GNU General Public (v2.0) license; and (b) binary, proprietary, or commercial licenses. Except for the licenses granted herein, You reserve all right, title, and interest in and to "The Contributions"."
But that's not the point of this comment not relevant to our current discussion. 
I would still like to know if you're interested on following conditions:
A: The airport does not suffer in terms of details and quality. I.E. all the lines are correct like they currently are (mostly correct) in the document, but more importantly in RL (gate lines taxiway side lines etc.) 
Really the only thing that would need editing are taxiways. (As for the center part of the taxiways being transparent this was due to the fact of rumors of all the middle sections of taxiways being renovated with concrete like in the south west corner near 13R. I do not know if this is still planned however.)
B: You will work off my current version of JFK. 
C: I still get to manage and update KJFK in the future.

I think those are reasonable demands.

**Comment by kilt46** [comment] 2017-06-09 20:02
The reason I brought this up is quite simple
a) What is in the Repo is not your airport, neither is it my airport. It can quite easily be written over by a future version technically by any editor. Many of the airports I have done in the past have been changed/improved. It does not matter it is a community process
b) One cannot place any 'demands' here

Anyway - the intent was to reduce the sandwich offering of build up of taxiways. This should reduce the size of the file and potential conflict in features. Where lines/gates etc are correctly placed they would just be carried over. Taxiways C/FB/.EE/DB need updating.

Hope this makes sense - Respectfully

**Comment by NickArt1342** [comment] 2017-06-09 20:30
You're missing my point about me being assigned to this issue currently and asking you to take over this issue and add those little corrections. With exactly those "demands" I made I would be willing to let you do that for the sake of the airport being finished significantly sooner than when I do it. My airport needing to be updated and being assigned to the issue has nothing to do with me giving FDS an unlimited irreversibel permission of usage of said intellectual property as per agreement citated above. I'm asking you to take over, if you agree to the points I stated. If not I'll do it myself.

**Comment by dushyants19** [comment] 2017-07-05 17:32
What's up with the sudden unassignment @NickArt1342? Should we fix/redo it?

**Comment by CptNathanHope** [comment] 2018-01-15 22:02
@Blently updates? Are you still willing to do this? Please let me know, thanks. – n

**Comment by CptNathanHope** [comment] 2018-01-27 02:07
JFK overhaul, please. Would recommend only veteran editors to tackle this one. May grab it at some point if no one else does.
– N

**Comment by kilt46** [comment] 2018-04-24 22:41
![image](https://user-images.githubusercontent.com/14023167/39217694-c835d974-47e6-11e8-8eb0-1e299a7bc982.png)

**Comment by kilt46** [comment] 2018-04-24 22:50
Wrong version loaded to repo?

**Comment by ryu12332** [comment] 2018-04-25 04:40
GitHub issue appears to have been resolved. Do follow up with further. - Epps

**Closed by ryu12332** 2018-04-25 04:40 UTC

**Comment by dushyants19** [comment] 2018-04-25 10:33
Why the heck are you signing your comments now? 😐

**Comment by kilt46** [comment] 2020-08-15 18:30
![image](https://user-images.githubusercontent.com/14023167/90319190-6e7c0300-defb-11ea-808e-66d6fa05ac40.png)

**Comment by kilt46** [comment] 2020-08-15 18:30
11L/31R now concrete
