### ISSUE TITLE
KORD-Chicago O'Hare International Airport-ILLINOIS-USA

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Airports#19] opened 2015-01-05 10:12 UTC

**Comment by Rotate-FDS** [comment] 2015-08-26 11:49
Have the ILS systems for 10L/28R and 10C/28C added in the update?

**Comment by Rotate-FDS** [comment] 2015-08-26 20:25
Whoever can edit ILS, please fix this.

**Comment by carmichaelalonso** [comment] 2015-08-26 20:52
For nav data stuff (like ILSs), probably best if you post on github.com/infiniteflightairportediting/navigation/issues :)

**Comment by Rotate-FDS** [comment] 2015-08-26 20:54
Thanks, I wasn't sure what that repository held.

**Comment by kilt46** [comment] 2015-12-12 19:20
Redoing the periphery of this one for therapy!

**Comment by kilt46** [comment] 2015-12-20 21:14
Done and publshed.

**Comment by Swang007** [comment] 2016-02-19 04:07
![slack for ios upload png](https://cloud.githubusercontent.com/assets/11000109/13166307/e0a36b94-d68b-11e5-8fdd-b3c998f1f8d0.jpeg)

Joe just sent me this. Apparently all taxiways are KORD are gone. Just checked the repo and the apt.dat file seems to be fine, in the sense that taxiways do show up in WED. @kilt46

**Comment by JohnPreston21** [comment] 2016-02-19 05:57
I can confirm this. I am at KORD now and it is nothing but grass covering the entire field.

**Comment by NickArt1342** [comment] 2016-02-19 07:59
I just checked it out and there is no taxiway at all, only lines and runways at KORD. @kilt46 you have any idea why?

**Comment by dushyants19** [comment] 2016-02-20 15:28
Fixed, check latest push

**Comment by PaulNielsen** [comment] 2016-10-04 17:52
Looks like runway 32R has been closed for good, pavement is still there tho. So 32L-14R has now been changed to 33-15. I would fix this if I could, but as I have told in Slack team and to Dush, my WED messes up something with Kilts gate stuff, even tho I have tried exporting in all different types, and both with WED beta and latest beta. So if anyone can fix this, it would be good! :)

**Comment by kilt46** [comment] 2016-10-05 02:23
![image](https://cloud.githubusercontent.com/assets/14023167/19099086/bb77fa28-8a78-11e6-90a7-07b4aba70f70.png)

**Comment by kilt46** [comment] 2016-10-05 02:23
![image](https://cloud.githubusercontent.com/assets/14023167/19099090/c97609f8-8a78-11e6-8621-82aed4c93feb.png)

**Comment by kilt46** [comment] 2016-10-05 02:23
Gates being reworked
![image](https://cloud.githubusercontent.com/assets/14023167/19099103/da44ef06-8a78-11e6-829f-6d0746fce668.png)

**Comment by kilt46** [comment] 2016-10-06 23:39
![image](https://cloud.githubusercontent.com/assets/14023167/19174416/367cfd14-8bf4-11e6-8cb0-35d17874bc70.png)

**Comment by Spinxzl** [comment] 2017-05-13 12:15
Runway 32L is missing hold short on 3rd taxiway, coordinates are slightly off. My computer is to slow to handle the size annoyingly 😡

**Comment by dushyants19** [comment] 2017-05-13 12:53
32L doesnt even exist.

**Comment by Spinxzl** [comment] 2017-05-13 12:55
Does in IF, must be 33 IRL,

**Comment by kilt46** [comment] 2017-06-06 23:07
![image](https://user-images.githubusercontent.com/14023167/26855830-ded925c0-4ae2-11e7-96d0-f3d6509a3e6e.png)

**Comment by kilt46** [comment] 2017-06-06 23:07
What is seen in LEGACY Infinite Flight is very different to what is currently released in Global. Global has the latest version.

**Comment by brunocr98** [comment] 2018-06-13 18:41
Redoing the airport in its totality; it's the best option to deal with the issues reported. Also, KORD is GP1. https://www.usatoday.com/story/travel/flights/todayinthesky/2017/08/08/80/549532001/

**Comment by kilt46** [comment] 2018-06-25 23:01
Buildings removed - great thx
Aircraft hangars - should all have a concrete base to represent them. Looks like they have all been removed.

**Comment by kilt46** [comment] 2018-06-26 01:54
![image](https://user-images.githubusercontent.com/14023167/41884659-f100f1aa-78b9-11e8-99f7-69fdffb4bec2.png)

**Comment by kilt46** [comment] 2018-07-06 22:51
The Northeast Cargo ramp gates actually have gate numbers: NE-1, NE-2, NE-3, all the way to NE-11, starting from the southwestern-most gate (which is currently named CARGO KOREAN AIR 01) and going counter clockwise. I would suggest naming them like ‘Northeast Cargo NE-1’ and not necessarily including an air cargo operator in the title because the stands are each used by multiple carriers.

Also, the handstands directly east of terminal 5 are named incorrectly. Remote M22 should be Hardstand M22A, remote M23 should be hardstand M22, remote M24 should be hardstand M22B, remote M25 should be hardstand M23, and then hardstands M24, M24A (A380 capable), and M25 aren’t even allocated any ramp starts.

Also, CARGO DELTA SC02 should be SC2A and CARGO DELTA SC04 should be SC2 because they are basically the same gate, only the former is for the B748. In short, the Southeast Cargo Gates from SC02 to SC10 are given to the wrong gates. SC10 I dont believe is even used anymore.

Also, why is almost all the pavement concrete? There are many asphalt patches that I noticed haven been model. Is it to reduce the amount of memory it takes up? To be honest, I have become really familiar with O’Hare because I live pretty close, but I currently don’t have the clout to make these edits because I haven’t submitted an airport for review yet (I’m currently working on KMSN, which should be done soon).

I just wanted to know when it would be possible for me to make edits to big Class B airport, specifically O’Hare, so I could be of extra help.

**Comment by kilt46** [comment] 2018-07-06 22:52
![image](https://user-images.githubusercontent.com/14023167/42403234-5f143bd2-8145-11e8-98b8-27bd134ad110.png)

**Comment by kilt46** [comment] 2018-07-06 22:56
![image](https://user-images.githubusercontent.com/14023167/42403316-f34b06d2-8145-11e8-98d2-325f71e0b0fc.png)

**Comment by kilt46** [comment] 2018-07-06 22:59
![image](https://user-images.githubusercontent.com/14023167/42403374-58413d5e-8146-11e8-803f-a23d4531ce83.png)

**Comment by kilt46** [comment] 2018-07-08 10:39
![image](https://user-images.githubusercontent.com/14023167/42418979-55cf6b82-8271-11e8-8512-125e27ffe3da.png)

**Comment by brunocr1050** [comment] 2021-01-06 04:31
@jakey20 will be adding the following to ORD airport:

- New de-icing pad west of the airport and update surrounding taxiways.
- Asphalt surfaces for existing taxiways.

*Other areas that need to be updated will be permitted if necessary.

**Closed** 2021-02-01 00:07 UTC
Labels: Being Redone, Priority 2

**Comment by kilt46** [comment] 2021-02-01 02:01
![image](https://user-images.githubusercontent.com/14023167/106406508-167c7e80-63ff-11eb-9312-0df406c39668.png)
